version: '3.9'

services:

  # Start postgres service and ensure that data is stored in a named or anonymous volume.
  falco_rules_baseline_mysql_db:  # ServiceName
    hostname: falco-mysql  # ← Aquí defines el hostname
    build:
      context: .  # Specify the Dockerfile location
      dockerfile: Dockerfile  # Dockerfile specification

    # Deployment options
    deploy:
      mode: replicated

      replicas: 1

    # image: 'bitnami/mysql:latest'  # Assign or build the service image.
    image: 'bitnami/mysql:8.0.34'

    container_name: falco_baseline_mysql_db
    ports:
      - "3306:3306"
    restart: always  # Ensures that the container is automatically restarted in case of failures

    environment:     # Bad security practice (Hardcoded credentials)
      MYSQL_DATABASE: test
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: pass

    volumes:
      - mysql_volume:/bitnami/mysql/:rw  # Volumen persistente para MySQL
      #- ./db-data/postgres/:/var/lib/postgresql/data/:rw  # Anonymous volume
      # - postgres_volume:/var/lib/postgresql/data/:rw  # Named volume
      # - mysql_data:/var/lib/mysql  # Volumen para persistencia de datos
volumes:
    mysql_volume:
